### PR TITLE
Fix issue localizing absent signal

### LINKED ISSUE #758: No such signal SIGSYS
```
[2017/02/02 06:05:10.710] No such signal: SIGSYS at C:/data/mci/837780107ff8f981dcc4113c65781360/perl5/lib/perl5/Test2/API/Instance.pm line 312.
[2017/02/02 06:05:10.711] No such signal: SIGSYS at C:/data/mci/837780107ff8f981dcc4113c65781360/perl5/lib/perl5/Test2/Util.pm line 84.
[2017/02/02 06:05:10.734] No such signal: SIGSYS at C:/data/mci/837780107ff8f981dcc4113c65781360/perl5/lib/perl5/Test2/API/Instance.pm line 312.
[2017/02/02 06:05:10.735] No such signal: SIGSYS at C:/data/mci/837780107ff8f981dcc4113c65781360/perl5/lib/perl5/Test2/Util.pm line 84.
```

This was observed on Strawberry Perl portable 5.14.4.  It's probably from ignoring SIGSYS, so that should probably be conditional on that signal being available per Config.pm.

### PR DESCRIPTION
**Pull request by exodist**
Fixes #758

@xdg can you take a peek at this?

### CODE REVIEW

File: lib/Test2/Util.pm [hunk 1]
```diff
@@ -143,6 +145,15 @@ sub pkg_to_file {
 
 sub ipc_separator() { "~" }
 
+BEGIN {
+    if ($Config{sig_name} =~ m/\bsys\b/) {
```
Comment (xdg) [inline lib/Test2/Util.pm]: At least on Mac and Linux where I've spot checked, sig_name contains uppercase values.  Maybe this should be a case-insensitive match?

**Comment by exodist** [comment]
Indeed, I would say I need to complete this PR with a test as well.
